services:
  fpams-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fpams-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Fpams@12345"
    ports:
      - "1433:1433"
    volumes:
      - fpams-sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Fpams@12345 -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  fpams-sql-data:
